### ISSUE TITLE
how to use sass

### ISSUE THREAD

**Issue by kobezone** [ElementUI/element-font-awesome#1]
can you offered demo how to use sass? when i use sass  element-ui & font-awesome it can't work

**Comment by kaiye** [comment]
Here is my sample code:

1. defined prefix and path variables
2. import entry scss file

```scss
[class^="el-icon-fa"], [class*=" el-icon-fa"] {
  display: inline-block;
  font: normal normal normal 14px/1 FontAwesome!important;
  font-size: inherit;
  text-rendering: auto;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
};

$fa-css-prefix: el-icon-fa;
$fa-font-path: "~@/../node_modules/font-awesome/fonts";

@import '~@/../node_modules/font-awesome/scss/font-awesome.scss';
```

**Comment by jpickwell** [comment]
Try the following:
```scss
// font-awesome: Concatenates with '/' between path and font name.
$fa-font-path: '~font-awesome/fonts';
$fa-css-prefix: el-icon-fa;

@import '~font-awesome/scss/font-awesome';

[class^='#{$fa-css-prefix}-'], [class*=' #{$fa-css-prefix}-'] {
  display: inline-block;
  font: normal normal normal #{$fa-font-size-base}/#{$fa-line-height-base} FontAwesome !important;
  font-size: inherit;
  text-rendering: auto;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
```

My project is using Webpack. Can't remember if the `~` prefix is Webpack or Sass specific.

**Comment by jpickwell** [comment]
I actually found a simpler option that allows FontAwesome's size classes to work.

```scss
// font-awesome: Concatenates with '/' between path and font name.
$fa-font-path: '~font-awesome/fonts';
$fa-css-prefix: el-icon-fa;

@import '~font-awesome/scss/font-awesome';

[class^='#{$fa-css-prefix}-'], [class*=' #{$fa-css-prefix}-'] {
  font-family: FontAwesome !important; // override ElementUI's icon font
}
```
